name: Deploy to AWS Elastic Beanstalk

on:
  push:
    branches:
      - main  # Change this to the branch you want to deploy from

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
        
    - name: Set up environment variables
      run: |
        echo "DB_URL=${{ secrets.DB_URL }}" >> $GITHUB_ENV
        echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> $GITHUB_ENV
        echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> $GITHUB_ENV
    - name: Build with Maven
      run: mvn -f pom.xml clean package  # Adjust Maven goals as needed

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
        
    - name: Create Application Version
      run: |
          aws elasticbeanstalk create-application-version \
            --application-name e-dhukan_ProductService \
            --version-label v1 \
            --source-bundle S3Bucket=elasticbeanstalk-us-east-2-767398148932,S3Key=target/${{ secrets.PROJECT_NAME }}

    - name: Deploy Application Version
      run: |
          aws elasticbeanstalk update-environment \
            --application-name e-dhukan_ProductService \
            --environment-name E-dhukanProductService-env \
            --version-label v1
