name: Java Spring Boot Build

on:
  push:
    branches:
      - main  # Change this to the branch you want to trigger the build on

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Build with Maven
      run: mvn -f pom.xml clean package  # Adjust Maven goals as needed

    - name: Archive built artifact
      uses: actions/upload-artifact@v2
      with:
        name: java-app
        path: target/*.jar  # Path to the built JAR file
